### ISSUE TITLE
PCB is not a functioning circuit

### ISSUE THREAD

**Issue by kasbah** [kitspace/ruler#14]
The traces at the bottom went missing, the vias at the top went missing   :confused: . In waaaaay too much of rush when I sent this off.

**Comment by badgeek** [comment]
so many open issues 😕 ... as this is the first pcb manufactured using svg2shenzhen, are there any specific svg2shenzhen related bug ?

**Comment by kasbah** [comment]
Ha no, svg2shenzhen is working great! Zones would useful but we know that. Well, one smaller thing maybe: would be good to make all the drawing "reference" and "value" texts invisible by default. I'll probably take a look at doing that soon. 

But mainly I just _really_ rushed it to try and have something to hand out at the Hackaday Belgrade conference (but it still didn't arrive on time in the end :rage:).
